# Generated by Django 4.1.7 on 2024-10-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_snippet_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
